### ISSUE TITLE
Home Assistant grumpy about hostnames

### ISSUE THREAD

**Issue by rohrsh** [pawlizio/my_velux#13]
On 2022.2:

- Detected integration that accessed discovery_info.get('hostname') instead of discovery_info.hostname; this will fail in version 2022.6. **Please report issue to the custom component author for my_velux using this method at custom_components/my_velux/config_flow.py, line 82: or not info.get("hostname")**
- Detected integration that accessed discovery_info['hostname'] instead of discovery_info.hostname; this will fail in version 2022.6. Please report issue to the custom component author for my_velux using this method at custom_components/my_velux/config_flow.py, line 83: or not info["hostname"].startswith("VELUX_KLF_LAN")
- Detected integration that accessed discovery_info.get('host') instead of discovery_info.host; this will fail in version 2022.6. Please report issue to the custom component author for my_velux using this method at custom_components/my_velux/config_flow.py, line 87: self._host = info.get("host")

**Comment by pawlizio** [comment]
This has been solved with the latest release 2.0
