### ISSUE TITLE
Home Assistant 2022.10

### ISSUE THREAD

**Issue by neildsb** [pawlizio/my_velux#16]
Hope this helps?

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 8:43:25 am (3 occurrences)
Last logged: 8:44:10 am

custom_components.velux.number::VeluxOpenOrientatoion is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.velux.number::VeluxCloseOrientatoion is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.miele.number::MieleNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by pawlizio** [comment]
This is now fixed with v.2.8
