### ISSUE TITLE
stopped working 2022.10.3

### ISSUE THREAD

**Issue by neildsb** [pawlizio/my_velux#17]
Hope this helps?

Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.0
Frontend 20221010.0 - latest

This error originated from a custom integration.

Logger: custom_components.velux
Source: custom_components/velux/__init__.py:38
Integration: Velux
First occurred: 7:37:16 am (5 occurrences)
Last logged: 7:39:09 am

Unable to connect to KLF200: [Errno 111] Connect call failed ('192.168.20.101', 51200)

Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 7:37:16 am (3 occurrences)
Last logged: 7:37:25 am

Config entry 'Velux' for velux integration not ready yet: [Errno 111] Connect call failed ('192.168.20.101', 51200); Retrying in background
Config entry 'Bedroom 1 fan' for tapo integration not ready yet: None; Retrying in background
Config entry 'Bathroom Electric Radiator HS100(UK)' for tplink integration not ready yet: Unable to connect to the device: 192.168.20.151: [Errno 113] Connect call failed ('192.168.20.151', 9999); Retrying in background

**Comment by dumpfheimer** [comment]
Are you sure this is not simpy a network error? Does it start working again when you roll back to a known working HA release?

**Comment by neildsb** [comment]
ah yes, jumped the gun, it's all good now and working with 22.10.3!!....needed to hard shutdown the VM rather than a reboot, also rebooted the KLF before booting up, a snapshot rollback to 22.10.2 was good hence i thought it was a 22.10.3 problem
