### ISSUE TITLE
Closing/Opening cover state

### ISSUE THREAD

**Issue by faizpuru** [pawlizio/my_velux#20]
Hey ! 
Thanks for your work, it's working great. Just one little detail : the cover entity does not change its state to opening/closing. it just updates to the states: closed/open. Is there some known limitation for that ? I can try to help if needed. 

Thanks again :)

**Comment by pawlizio** [comment]
Hey @faizpuru, I have added your request. Your are free to test the new beta release 2.8.5.

**Comment by faizpuru** [comment]
I just tried it and it's working well ! 
Thank you so much for this quick fix.
