### ISSUE TITLE
Incorrect pyvlx version dependency?

### ISSUE THREAD

**Issue by apeeters** [pawlizio/my_velux#21]
In https://github.com/pawlizio/my_velux/commit/8db2005a9f512f23f03fc8cffd06674903be0c69 the pyvlx version was changed from `0.2.21` to` 1.2.21`, however that version does not seem to exist. Might be a typo?

**Comment by pawlizio** [comment]
@apeeters no, even 0.2.21 does not yet exist yet. Official pyvlx is at 0.2.20. With that code I just want to ensure that my custom will not use official pyvlx in the near future, but mine at https://github.com/pawlizio/pyvlx

I have some modifications which first needs to be merged to official pyvlx.
