### ISSUE TITLE
Opening/Closing state stays on indefinitely

### ISSUE THREAD

**Issue by DarkWarden85** [pawlizio/my_velux#22]
Hi,

First of all thank you for your hard work realising this integration. So far it works well for me, except that there seems to be an issue with the opening/closing state.
When I open or close the cover, the cover itself correctly assumes the opening or closing state. However, the cover then never exits the opening or closing state, regardless if the cover is fully opened or closed. The only way to make the cover get its correct state is to call stop on it.

Here's an image where one can see that the cover is in the state opening. The current position is already 100% at that point. It even updates its position to 100% once it has fully opened but it's state remains opening.
![image](https://user-images.githubusercontent.com/79642261/222147439-02e61660-f4ce-4943-90a1-fcccb5e7c2cf.png)

Furthermore, if I use the position slider to move the cover, the cover starts moving and correctly displays opening/closing, but again never leaves this state even if the cover has already reached the position and stopped by itself. Note in the picture below that the cover has been in the state opening for 7 minutes (it isn't that slow :) ).
![image](https://user-images.githubusercontent.com/79642261/222148982-e2fcee4b-776e-4eef-b1e4-b8febe720590.png)

I have included a debug log during the operation of the cover.
[home-assistant_velux_2023-03-01T12-59-48.627Z.log](https://github.com/pawlizio/my_velux/files/10861294/home-assistant_velux_2023-03-01T12-59-48.627Z.log)

I am currently running Home Assistant OS on a Raspberry Pi 4
Home Assistant version: 2023.2.5
Velux integration version: 2.8.5

The KLF 200 Gateway is rebooted via Power plug upon every restart of Home Assistant.

It would be great if you (@pawlizio) could have a look at this.

**Comment by pawlizio** [comment]
Hi @DarkWarden85 

I found the issue, even if your cover finished the job, the current_poistion was different from the target_position.
Actually I used just those two values and compared them to say a cover is opening/closing or not moving. 

Luckily pvlxc provides also an operating state which I used now.  Opening/Closing is now only set if the state=EXECUTING.

With the latest release this should be fixed now. 
Please update to latest custom component and test.

**Comment by DarkWarden85** [comment]
Hi @pawlizio 

I updated to the newest version and can confirm that the issue is now resolved. It works beautifully.

I cannot tell you how much I appreciate getting such good support from you. It was the right choice to switch from the official Velux integration to your custom component.

I will close the issue now.
