### ISSUE TITLE
Request: expose of limits values

### ISSUE THREAD

**Issue by Diddlik** [pawlizio/my_velux#31]
Is it possible to specify the limit values?Maybe as attributes or as sensors?In pyvlx it is already present. So you can tempalten it as a rain sensor:
```
# Read limits of windows   
# limit = await pyvlx.nodes['Bath'].get_limitation()    
# limit.min_value    
# limit.max_value

```
I also found the other implementation where it is in there, but is not maintained further: https://github.com/mago0211/home-assistant-custom-component-velux2

**Comment by pawlizio** [comment]
I added the VeluxWindow from the link you posted, please install latest prelease version and check if this works. I don't have windows to test this.

**Comment by Diddlik** [comment]
Should I update my_velux to prerelase or pyvlx?

**Comment by Diddlik** [comment]
ok, it works and windows status is updated automatically.
![grafik](https://github.com/pawlizio/my_velux/assets/6010713/27f614ec-1508-46e2-812b-229294df9ca3)

**Comment by pawlizio** [comment]
I assume this can be closed then.
