### ISSUE TITLE
Why not helping to making official HA integration better, instead of having a separate custom integration ?

### ISSUE THREAD

**Issue by crivchri** [pawlizio/my_velux#35]

**Comment by pawlizio** [comment]
You are free to use my custom and create PR into HA. I simply don't have time to dive in, learn python module testing and so on. There are some requirements from Home Assistant team which should be fulfilled.

**Comment by crivchri** [comment]
Hi @pawlizio,

Thank you a lot for your explanation. Unfortunately, I'm not experienced enough to submit a PR in HA.
