### ISSUE TITLE
115.0 velux component

### ISSUE THREAD

**Issue by pergolafabio** [pawlizio/my_velux#4]
after updating to 115.0 , seems its discovering the velux again, while already running this custom
anyone else seeing this too ? i cant ignore it seems

**Comment by pergolafabio** [comment]
see also here for screenshot

https://community.home-assistant.io/t/0-115-b-day-release-media-browser-tags-automations-wth/227518/56?u=pergola.fabio

**Comment by pawlizio** [comment]
Integration completely reworked, should be solved now
