### ISSUE TITLE
My devices were duplicated after an update, after deleting inactive entities I'm left with empty device entries

### ISSUE THREAD

**Issue by spitfire** [pawlizio/my_velux#41]
My devices were duplicated after an update

<img width="1809" alt="Zrzut ekranu 2024-01-26 o 10 43 27" src="https://github.com/pawlizio/my_velux/assets/42872/bc2a2af6-38cc-48d5-ad76-8303e8981d67">

after deleting inactive entities from device nodes I'm left with empty device entries (which I can't delete):
<img width="1499" alt="Zrzut ekranu 2024-01-26 o 10 44 03" src="https://github.com/pawlizio/my_velux/assets/42872/0e4c235c-094c-4acc-9fb9-d3b199c80e53">

And the actual (working) devices with entities:
<img width="1410" alt="Zrzut ekranu 2024-01-26 o 10 44 26" src="https://github.com/pawlizio/my_velux/assets/42872/afa09951-f1d2-4153-89c7-61b60c7f416a">

Can you please implement deletion of them?

**Comment by pawlizio** [comment]
Have you tried to restart HA?

**Comment by spitfire** [comment]
I have restarted it a lot of times since that happened. Some integrations offer that functionality (as seen on the below screenshot), isn't this something that you can implement?
<img width="1078" alt="Zrzut ekranu 2024-01-26 o 18 58 33" src="https://github.com/pawlizio/my_velux/assets/42872/9e7b3204-cbe5-4c59-b972-4da431e301e6">

**Comment by spitfire** [comment]
I still have devices with no entities I can't delete.

**Comment by pawlizio** [comment]
Have you tried to delete all inactive velux entities through the entities page, not directly the devices?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by spitfire** [comment]
How can I do it for a device that has no entities? 🤔 
<img width="1230" alt="Zrzut ekranu 2024-05-15 o 22 35 34" src="https://github.com/pawlizio/my_velux/assets/42872/4e70ed55-b054-444a-acb7-01962c03dc24">
Some other integrations (like MQTT) offer that option (the three dot menu in the info section)
<img width="1065" alt="Zrzut ekranu 2024-05-15 o 22 36 12" src="https://github.com/pawlizio/my_velux/assets/42872/58e68f70-4d41-46a4-a61d-af59e69f2f24">

**Comment by pawlizio** [comment]
Please check the entities page for all velux integration entities whether there any unavailable entities or with other issues and delete them. Actualy devices can only be created for entities, not sure what is happened here.

**Comment by pawlizio** [comment]
Try the pre-release 2.9.12, it should allow to detele devices now.

**Comment by spitfire** [comment]
Looks a bit different than in other integrations, but it seems to have worked for me flawlessly. Thanks!
