### ISSUE TITLE
This custom still needed?

### ISSUE THREAD

**Issue by pergolafabio** [pawlizio/my_velux#43]
Hi @pawlizio 

I saw you were also working on the PR thats coming today in new 2024.3 

Is this custom still needed afterwards? Is everything included in this custom also in the official core?
I use the rain sensor especially, the "limitation_min" 

![image](https://github.com/pawlizio/my_velux/assets/43251136/94b78afe-bf5f-456b-a95c-38bdb94a900a)

**Comment by pergolafabio** [comment]
perfect, so for now, the "limitation_min" is not yet avaible?

**Comment by neildsb** [comment]
I have moved over to the official integration; many thank for all your support over the years @pawlizio

**Comment by jotbed** [comment]
I will stay. My blinds aren't Set Up correct in the official addon.

**Comment by andrazek** [comment]
I would love to see limitation_min in offical addon, so we can finally access rain sensors! Are there any itentions to add this in PR? Thanks.
