### ISSUE TITLE
[Feature request] Support silent mode

### ISSUE THREAD

**Issue by mathieu-mp** [pawlizio/my_velux#6]
Hi, Big thanks for your job on klf200 !

Would you consider supporting silent mode ?
Silent mode is a slow speed motor mode on Somfy "S&SO RS100 io" motors. "Smoove RS100 io" remote has a button to enable this feature, but I cannot tell if klf200 supports it.

Regards, Mathieu.

**Comment by pawlizio** [comment]
This feature has to be implemented in pyvlx module first:  [https://github.com/Julius2342/pyvlx](url)

**Comment by mathieu-mp** [comment]
I created the corresponding issue: https://github.com/Julius2342/pyvlx/issues/60
I should have started there, thank your for your answer

**Comment by mathieu-mp** [comment]
The klf200 API doc mentions a removal of the motor speed endpoint
We won't go any further on this feature with the current firmware
